ci: build cairo contracts

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -77,6 +77,35 @@ jobs:
         run: |
           cd ${{ matrix.package }}
           poetry install
+
+      - name: Cache contracts
+        id: cache-contracts
+        uses: actions/cache@v3
+        with:
+          path: ./pragma-oracle/target
+          key: ${{ runner.os }}-contracts-${{ hashFiles('./pragma-oracle/src', 'poetry.lock') }}
+
+      - uses: software-mansion/setup-scarb@v1
+        with:
+          tool-versions: pragma-oracle/.tool-versions
+
+      - name: Compile contracts
+        if: steps.cache-contracts.outputs.cache-hit != 'true'
+        working-directory: ./pragma-oracle
+        run: |
+          scarb -V
+          scarb build
+
+      - name: Check ABIs are up-to-date
+        run: |
+          # Find and compare *.sierra.json files in both directories
+          for file in $(find ./pragma-oracle/target/dev -type f -name "*.sierra.json"); do
+            # Extract the relative path of the file for comparison
+            rel_path=${file#./pragma-oracle/target/dev}
+            # Use diff to compare the file with its counterpart in the SDK directory
+            diff "$file" "pragma/core/abis$rel_path" || (echo "Error: $rel_path in pragma-oracle/target does not match with pragma/core/abis/" && exit 1) 
+          done
+
       - name: Install rust
         run: |
           curl https://sh.rustup.rs -sSf | sh -s -- -y
